;; Contrived example to display usage of CONF directives.

CONF:BEGIN
  STATE:INITIAL START
  STATE:ACCEPT ACC
  STATE:REJECT REJ
  STATE:ERROR ERR
  STATE:EXTRA-HALTS HALT1 HALT2
CONF:END

START 0 -> ACC 0 S
START 1 -> REJ 1 S
START 2 -> ERR 2 S
START 3 -> HALT1 3 S
START 4 -> HALT2 4 S
